# Generated by Django 2.2.1 on 2019-05-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasksummary',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('taskname', models.CharField(max_length=60)),
                ('taskcreatedate', models.DateTimeField(auto_now_add=True)),
                ('taskeditdate', models.DateTimeField(auto_now=True)),
                ('taskdetails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testresult',
            fields=[
                ('resultid', models.AutoField(primary_key=True, serialize=False)),
                ('teststarttime', models.DateTimeField()),
                ('testendtime', models.DateTimeField()),
                ('testtime', models.CharField(max_length=20)),
                ('testusernum', models.IntegerField()),
                ('testusersec', models.IntegerField()),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtask.Tasksummary')),
            ],
        ),
    ]
